create table noteful_notes (
    id integer primary key generated by default as identity,
    note_name text unique not null,
    modified TIMESTAMPTZ default now() not null,
    folder_id integer references noteful_folders(id) not null,
    content text not null
)